# Generated by Django 4.2.6 on 2023-11-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='developers'),
        ),
    ]
