# Generated by Django 4.2.6 on 2023-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_developers_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='edad',
            new_name='age',
        ),
    ]
