# Generated by Django 4.2.6 on 2023-11-14 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_rename_edad_developers_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatar',
            new_name='Avatares',
        ),
    ]
