# Generated by Django 4.2.6 on 2023-11-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_avatar_avatares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatares',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
